### ISSUE TITLE
Support for Swipe Navigation in Notes Read-Only Page

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#217]
Implement swipe navigation in the notes read-only page, similar to how apps like Gmail allow users to swipe left or right to navigate to the next or previous email. In DiaryVault, this feature should enable users to swipe between notes in read-only mode. Diaryault supports read mode and write mode for a note, we do not want this feature in the write mode to prevent potential data loss if unsaved changes are present when navigating away from a note.

- **Widget Involved:**
  - `lib/features/notes/presentation/pages/note_read_only_page.dart`
  - `lib/features/notes/presentation/widgets/note_preview_card.dart`
  - `lib/core/pages/home_page.dart`

- **Current Setup:**
  - The `NotesReadOnlyPage` widget currently takes a `note.id` as a parameter and loads the corresponding note from the database.
  - The `NotesFetchState` holds the list of notes fetched from the database to display on the home page.

**Proposed Solution:**

1. **Utilize `PageView`:**
   - Use Flutter's [`PageView`](https://api.flutter.dev/flutter/widgets/PageView-class.html) widget to enable swipe navigation between notes.
   
2. **Pass Additional Parameters:**
   - Pass  Listview's`index` as parameter to `NotePreviewCard` widget from home screen. Index Represents the position of current note from the list.
   - Modify the `NotesReadOnlyPage` to accept an additional route parameter `index`, representing the position of the current note in the list. Actual logic for swipe natigation will be in `NotesReadOnlyPage`. 
   
4. **Access Next and Previous Notes:**
   - Use the `NotesFetchState` to access the list of note IDs.
   - During a swipe event, determine the next or previous note by incrementing or decrementing the `index`.

**Tasks:**

- [ ] Modify `NotePreviewCard` to accept an `index` parameter from home screen's Listview. 
- [ ] Modify `NotesReadOnlyPage` to accept `index`as route parameter and pass `index` from `NotePreviewCard` which will serve as initial index for swipe navigation. 
- [ ] Implement a `PageView` in  `NotesReadOnlyPage` that allows swiping between notes in read-only mode.
- [ ] Ensure that the notes load correctly when swiped left or right.

**Comment by zdoryyk** [comment]
Hi again @SankethBK I would like to try

**Comment by zdoryyk** [comment]
@SankethBK  Hi again, i have done this task, can I add?

**Comment by SankethBK** [comment]
Hi @zdoryyk , please raise the PR
