### ISSUE TITLE
Cleanup unused images and convert PNG to Webp

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#227]
All images used in the project are located in the `assets/images` folder. Currently, all of these images are in **PNG format**, which is increasing the overall app size. We need to:

1. **Convert all PNG images to WebP format** to reduce file size. You can use tools like [CloudConvert](https://cloudconvert.com/png-to-webp) for the conversion.
2. **Update the file paths** in the project wherever these images are used.
3. **Identify and delete unused images** to further reduce the app size.

### Tasks:
- [ ] Convert all PNG images in the `assets/images` folder to WebP format.
- [ ] Replace all PNG image paths in the code with the corresponding WebP paths.
- [ ] Identify and remove any unused images from the `assets/images` folder.

### Resources:
- PNG to WebP Conversion Tool: [CloudConvert](https://cloudconvert.com/png-to-webp)

**Comment by Prakharpan-dey** [comment]
.take

**Comment by Prakharpan-dey** [comment]
@SankethBK mind checking this whenever you are available
